/**
 * Excel (.xlsx) Export — NZTA Spec 6.1.2
 * Web: builds XLSX locally with the `xlsx` library and triggers Blob download.
 * Native iOS: POSTs log data to server endpoint, receives download URL, opens in Safari.
 * NO expo-file-system or expo-sharing imports.
 */
import * as XLSX from "xlsx";
import { Platform, Linking } from "react-native";
import { type DailyLog } from "./logbook-storage";
import { type DriverType } from "./local-auth";
import { getApiBaseUrl } from "@/constants/oauth";

export type ExcelExportOptions = {
  logs: DailyLog[];
  driverName: string;
  licenceNumber: string;
  vehicleRego: string;
  driverType: DriverType;
  password?: string;
};

// ─── Helper Functions ─────────────────────────────────────────────────────────
function formatHM(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}
function fmtTime(isoString: string): string {
  const d = new Date(isoString);
  return d.toLocaleTimeString("en-NZ", { hour: "2-digit", minute: "2-digit", hour12: true });
}
function computeDrivingSeconds(log: DailyLog): number {
  let ms = 0;
  const events = log.events;
  for (let i = 0; i < events.length - 1; i++) {
    const current = events[i];
    const next = events[i + 1];
    if (current.type === "shift_start" || current.type === "break_end" || current.type === "other_work_end") {
      ms += new Date(next.timestamp).getTime() - new Date(current.timestamp).getTime();
    }
  }
  return Math.floor(ms / 1000);
}
function computeOtherWorkSeconds(log: DailyLog): number {
  let ms = 0;
  const events = log.events;
  for (let i = 0; i < events.length - 1; i++) {
    if (events[i].type === "other_work_start") {
      ms += new Date(events[i + 1].timestamp).getTime() - new Date(events[i].timestamp).getTime();
    }
  }
  return Math.floor(ms / 1000);
}
function computeBreakSeconds(log: DailyLog): number {
  let ms = 0;
  const events = log.events;
  for (let i = 0; i < events.length - 1; i++) {
    if (events[i].type === "break_start") {
      ms += new Date(events[i + 1].timestamp).getTime() - new Date(events[i].timestamp).getTime();
    }
  }
  return Math.floor(ms / 1000);
}

export async function generateAndShareExcel(options: ExcelExportOptions): Promise<void> {
  const { logs, driverName, licenceNumber, vehicleRego, driverType, password } = options;

  if (Platform.OS === "web") {
    // Web: build workbook locally with xlsx library and trigger download
    const sorted = [...logs].sort((a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime());

    // Sheet 1: Summary
    const summaryData = [
      ["DRIVE LEGAL \u2014 Electronic Logbook Export"],
      [""],
      ["Driver Name", driverName],
      ["Licence Number", licenceNumber],
      ["Vehicle Rego", vehicleRego],
      ["Driver Type", driverType === "goods" ? "Goods Service (5.5hr)" : "Passenger Service (7hr)"],
      ["Export Date", new Date().toLocaleDateString("en-NZ")],
      ["Total Shifts", sorted.length.toString()],
      [""],
      ["Generated by Drive Legal v1.0 \u2014 Electronic Logbook built to NZTA Work Time and Logbooks Rule requirements"],
    ];
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    summarySheet["!cols"] = [{ wch: 20 }, { wch: 40 }];

    // Sheet 2: Shift Records
    const shiftHeaders = [
      "Date", "Shift Start", "Shift End", "Driving Time", "Other Work",
      "Break Time", "Total Work", "Start Location", "End Location",
      "Start Odometer", "End Odometer", "Distance (km)", "Amended", "Rest Override Note",
    ];
    const shiftRows = sorted.map((log) => {
      const drivingSec = computeDrivingSeconds(log);
      const otherSec = computeOtherWorkSeconds(log);
      const breakSec = computeBreakSeconds(log);
      const totalSec = log.totalWorkSeconds;
      return [
        log.date,
        fmtTime(log.startTime),
        fmtTime(log.endTime),
        formatHM(drivingSec),
        formatHM(otherSec),
        formatHM(breakSec),
        formatHM(totalSec),
        log.startLocation?.displayName ?? "",
        log.endLocation?.displayName ?? "",
        log.startOdometer ?? "",
        log.endOdometer ?? "",
        log.distanceKm ?? "",
        log.amendments && log.amendments.length > 0 ? "Yes" : "No",
        log.restOverrideNote ?? "",
      ];
    });
    const shiftSheet = XLSX.utils.aoa_to_sheet([shiftHeaders, ...shiftRows]);
    shiftSheet["!cols"] = shiftHeaders.map(() => ({ wch: 16 }));

    // Build workbook
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");
    XLSX.utils.book_append_sheet(wb, shiftSheet, "Shift Records");

    // Generate binary and trigger download
    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
    const blob = new Blob([wbout], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `DriveLegal_Logbook_${new Date().toISOString().split("T")[0]}.xlsx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  } else {
    // Native iOS: POST to server, get download URL, open in Safari
    const apiBase = getApiBaseUrl();
    const resp = await fetch(`${apiBase}/api/export/excel`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ logs, driverName, licenceNumber, vehicleRego, driverType, password }),
    });
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({ error: "Server error" }));
      throw new Error(err.error || "Failed to generate Excel on server.");
    }
    const { url } = await resp.json();
    if (!url) throw new Error("No download URL returned from server.");
    await Linking.openURL(url);
  }
}
