/**
 * Server-side password-protected Excel export endpoint.
 * Uses xlsx-populate which supports real AES encryption.
 * SheetJS community edition silently ignores the password option on web.
 *
 * POST /api/export/excel-protected
 * Body: { logs, driverName, licenceNumber, vehicleRego, driverType, password }
 * Response: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet (binary)
 */
import { Router } from "express";
import { createRequire } from "module";

// xlsx-populate is a CommonJS module. In an ESM context (esbuild --format=esm),
// top-level require() is not available. Use createRequire to load it safely.
const _require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-var-requires
const XlsxPopulate = _require("xlsx-populate");

export const excelProtectedRouter = Router();

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-NZ", { day: "2-digit", month: "2-digit", year: "numeric" });
}

function formatTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleTimeString("en-NZ", { hour: "2-digit", minute: "2-digit", hour12: false });
}

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  return `${h}h ${m}m`;
}

type EventType = "shift_start" | "shift_end" | "break_start" | "break_end" | "other_work_start" | "other_work_end";

interface LogEvent {
  type: EventType;
  timestamp: string;
  location?: { displayName?: string };
  odometer?: number;
  note?: string;
}

interface DailyLog {
  startTime: string;
  endTime: string;
  events: LogEvent[];
  startOdometer?: number;
  endOdometer?: number;
  amendments?: Array<{ timestamp?: string; field?: string; oldValue?: string; newValue?: string; reason?: string }>;
  hashChainValid?: boolean;
  restOverrideFlagged?: boolean;
  restOverrideNote?: string;
}

function computeSeconds(log: DailyLog, startTypes: EventType[]): number {
  let ms = 0;
  const events = log.events;
  for (let i = 0; i < events.length - 1; i++) {
    if (startTypes.includes(events[i].type as EventType)) {
      ms += new Date(events[i + 1].timestamp).getTime() - new Date(events[i].timestamp).getTime();
    }
  }
  return Math.floor(ms / 1000);
}

excelProtectedRouter.post("/", async (req, res) => {
  try {
    const { logs, driverName, licenceNumber, vehicleRego, driverType, password } = req.body as {
      logs: DailyLog[];
      driverName: string;
      licenceNumber: string;
      vehicleRego: string;
      driverType: string;
      password: string;
    };

    if (!logs || !Array.isArray(logs) || logs.length === 0) {
      res.status(400).json({ error: "No log data provided." });
      return;
    }
    if (!password || password.trim().length === 0) {
      res.status(400).json({ error: "Password is required for protected export." });
      return;
    }

    const sorted = [...logs].sort(
      (a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime()
    );

    // ─── Build workbook with xlsx-populate ───────────────────────────────────
    const wb = await XlsxPopulate.fromBlankAsync();

    // ── Sheet 1: Summary ──────────────────────────────────────────────────────
    const summarySheet = wb.sheet(0).name("Summary");
    const summaryRows = [
      ["DRIVE LEGAL — Electronic Logbook Export (Password Protected)"],
      [""],
      ["Driver Name", driverName],
      ["Licence Number", licenceNumber],
      ["Vehicle Rego", vehicleRego],
      ["Driver Type", driverType === "goods" ? "Goods Service (5.5hr)" : "Passenger Service (7hr)"],
      ["Export Date", new Date().toLocaleDateString("en-NZ")],
      ["Total Shifts", sorted.length],
      [""],
      ["Generated by Drive Legal v1.0 — Electronic Logbook built to NZTA Work Time and Logbooks Rule requirements"],
      ["NZTA Spec 6.1.4: Password-protected bulk export"],
    ];
    summaryRows.forEach((row, ri) => {
      row.forEach((val, ci) => {
        summarySheet.cell(ri + 1, ci + 1).value(val);
      });
    });
    summarySheet.cell("A1").style({ bold: true, fontSize: 13 });
    summarySheet.column("A").width(25);
    summarySheet.column("B").width(45);

    // ── Sheet 2: Shift Records ────────────────────────────────────────────────
    wb.addSheet("Shift Records");
    const shiftSheet = wb.sheet("Shift Records");
    const shiftHeaders = [
      "Date", "Shift Start", "Shift End", "Driving Time", "Other Work",
      "Break Time", "Total Work", "Start Location", "End Location",
      "Start Odometer", "End Odometer", "Distance (km)", "Hash Verified", "Amended", "Rest Override Note",
    ];
    shiftHeaders.forEach((h, ci) => {
      shiftSheet.cell(1, ci + 1).value(h).style({ bold: true, fill: "003366", fontColor: "FFFFFF" });
    });
    sorted.forEach((log, ri) => {
      const drivingSec = computeSeconds(log, ["shift_start", "break_end", "other_work_end"]);
      const otherSec = computeSeconds(log, ["other_work_start"]);
      const breakSec = computeSeconds(log, ["break_start"]);
      const totalSec = Math.floor(
        (new Date(log.endTime).getTime() - new Date(log.startTime).getTime()) / 1000
      );
      const startLoc = log.events[0]?.location?.displayName || "—";
      const endLoc = log.events[log.events.length - 1]?.location?.displayName || "—";
      const row = [
        formatDate(log.startTime),
        formatTime(log.startTime),
        formatTime(log.endTime),
        formatDuration(drivingSec),
        formatDuration(otherSec),
        formatDuration(breakSec),
        formatDuration(totalSec),
        startLoc,
        endLoc,
        log.startOdometer ?? "—",
        log.endOdometer ?? "—",
        log.startOdometer != null && log.endOdometer != null
          ? log.endOdometer - log.startOdometer
          : "—",
        log.hashChainValid !== false ? "✓" : "✗",
        log.amendments && log.amendments.length > 0 ? "Yes *" : "No",
        log.restOverrideFlagged && log.restOverrideNote ? `REST OVERRIDE: ${log.restOverrideNote}` : "",
      ];
      row.forEach((val, ci) => shiftSheet.cell(ri + 2, ci + 1).value(val));
      // Highlight override rows in amber
      if (log.restOverrideFlagged) {
        for (let ci = 0; ci < row.length; ci++) {
          shiftSheet.cell(ri + 2, ci + 1).style({ fill: "FFFBEB" });
        }
      }
    });
    shiftHeaders.forEach((_, ci) => shiftSheet.column(ci + 1).width(16));

    // ── Sheet 3: Event Timeline ───────────────────────────────────────────────
    wb.addSheet("Event Timeline");
    const eventSheet = wb.sheet("Event Timeline");
    const eventHeaders = ["Date", "Time", "Event Type", "Location", "Odometer", "Note"];
    eventHeaders.forEach((h, ci) => {
      eventSheet.cell(1, ci + 1).value(h).style({ bold: true, fill: "003366", fontColor: "FFFFFF" });
    });
    const typeLabels: Record<string, string> = {
      shift_start: "Shift Start", shift_end: "Shift End",
      break_start: "Break Start", break_end: "Break End",
      other_work_start: "Other Work Start", other_work_end: "Other Work End",
    };
    let eventRow = 2;
    for (const log of sorted) {
      for (const event of log.events) {
        const row = [
          formatDate(event.timestamp),
          formatTime(event.timestamp),
          typeLabels[event.type] || event.type,
          event.location?.displayName || "—",
          event.odometer ?? "—",
          event.note || "",
        ];
        row.forEach((val, ci) => eventSheet.cell(eventRow, ci + 1).value(val));
        eventRow++;
      }
    }
    eventHeaders.forEach((_, ci) => eventSheet.column(ci + 1).width(20));

    // ── Sheet 4: Amendments ───────────────────────────────────────────────────
    wb.addSheet("Amendments");
    const amendSheet = wb.sheet("Amendments");
    const amendHeaders = ["Shift Date", "Amendment Date", "Field Changed", "Old Value", "New Value", "Reason"];
    amendHeaders.forEach((h, ci) => {
      amendSheet.cell(1, ci + 1).value(h).style({ bold: true, fill: "003366", fontColor: "FFFFFF" });
    });
    let amendRow = 2;
    for (const log of sorted) {
      if (log.amendments && log.amendments.length > 0) {
        for (const amend of log.amendments) {
          const row = [
            formatDate(log.startTime),
            amend.timestamp ? `${formatDate(amend.timestamp)} ${formatTime(amend.timestamp)}` : "—",
            amend.field || "—",
            amend.oldValue || "—",
            amend.newValue || "—",
            amend.reason || "—",
          ];
          row.forEach((val, ci) => amendSheet.cell(amendRow, ci + 1).value(val));
          amendRow++;
        }
      }
    }
    amendHeaders.forEach((_, ci) => amendSheet.column(ci + 1).width(20));

    // ── Write with password encryption ───────────────────────────────────────
    const buffer: Buffer = await wb.outputAsync({ password: password.trim() });

    const fileName = `DriveLegal_Export_${driverName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.xlsx`;
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);
    res.setHeader("Content-Length", buffer.length);
    res.send(buffer);
  } catch (err: unknown) {
    console.error("[excel-protected] Error:", err);
    const msg = err instanceof Error ? err.message : "Failed to generate protected Excel file.";
    res.status(500).json({ error: msg });
  }
});
